name: Training
sorting: a
folder: null
type: Item
_id: FQAUMNkcagdBLURJ
sort: 200000
color: '#4d0a0a'
flags: {}
_stats:
  systemId: crucible
  systemVersion: 0.6.2
  coreVersion: '11.295'
  createdTime: null
  modifiedTime: 1682387469635
  lastModifiedBy: AnoypGxxNIMOS0XY
_key: '!folders!FQAUMNkcagdBLURJ'

